DentElora/Controllers/AboutUsController.cs
using DentElora.Data;
using Microsoft.AspNetCore.Mvc;

namespace DentElora.Controllers
{
    public class AboutUsController : Controller
    {
        private readonly DatabaseContext _context;

        public AboutUsController(DatabaseContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var model=_context.AboutUs.FirstOrDefault();
            return View(model);
        }
    }
}

DentElora/Controllers/TreatmentsController.cs
using DentElora.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DentElora.Controllers
{
    public class TreatmentsController : Controller
    {
        private readonly DatabaseContext _context;

        public TreatmentsController(DatabaseContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            var model =await _context.Treatments.ToListAsync();

            return View(model);
        }
        [Route("tedavi/{slug}")]
        public async Task<IActionResult> Detail(string slug)
        {
            var model = await _context.Treatments
    .FirstOrDefaultAsync(x => x.Slug == slug);

            if (model == null)
                return NotFound();

            return View(model);
        }
    }
}

DentElora/Areas/Admin/Views/Shared/_adminLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DentElora</title>



    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/responsive.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DentElora</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Main" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Contacts" asp-action="Index">İletişim</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Doctors" asp-action="Index">Doktorlar</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="FAQs" asp-action="Index">SSS</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Galleries" asp-action="Index">Galeri</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Sliders" asp-action="Index">Slider</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Treatments" asp-action="Index">Tedaviler</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="TreatmentPhotoes" asp-action="Index">Tedavi Resimleri</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Users" asp-action="Index">Kullanıcı</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="HomeInfoes" asp-action="Index">Anasayfa Bilgi</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Services" asp-action="Index">Hizmetler</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="AboutUs" asp-action="Index">Hakkımızda</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Login" asp-action="Logout">Oturumu Kapat</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - DentElora - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="@Url.Content("~/js/jquery.js")"></script>
    <script src="@Url.Content("~/js/wow.min.js")"></script>
    <script src="@Url.Content("~/js/bootstrap.min.js")"></script>
    <script src="@Url.Content("~/js/jquery.bxslider.min.js")"></script>
    <script src="@Url.Content("~/js/jquery.countTo.js")"></script>
    <script src="@Url.Content("~/js/owl.carousel.min.js")"></script>
    <script src="@Url.Content("~/js/validation.js")"></script>
    <script src="@Url.Content("~/js/jquery.mixitup.min.js")"></script>
    <script src="@Url.Content("~/js/jquery.easing.min.js")"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAHzPSV2jshbjI8fqnC_C4L08ffnj5EN3A"></script>
    <script src="@Url.Content("~/js/gmaps.js")"></script>
    <script src="@Url.Content("~/js/map-helper.js")"></script>
    <script src="@Url.Content("~/js/jquery.fitvids.js")"></script>
    <script src="@Url.Content("~/assets/jquery-ui-1.11.4/jquery-ui.js")"></script>
    <script src="@Url.Content("~/assets/language-switcher/jquery.polyglot.language.switcher.js")"></script>
    <script src="@Url.Content("~/js/jquery.fancybox.pack.js")"></script>
    <script src="@Url.Content("~/js/jquery.appear.js")"></script>
    <script src="@Url.Content("~/js/isotope.js")"></script>
    <script src="@Url.Content("~/js/jquery.prettyPhoto.js")"></script>
    <script src="@Url.Content("~/assets/timepicker/timePicker.js")"></script>
    <script src="@Url.Content("~/assets/bootstrap-sl-1.12.1/bootstrap-select.js")"></script>
    <script src="@Url.Content("~/assets/revolution/js/jquery.themepunch.tools.min.js")"></script>
    <script src="@Url.Content("~/assets/revolution/js/jquery.themepunch.revolution.min.js")"></script>
    <script src="@Url.Content("~/assets/revolution/js/extensions/revolution.extension.actions.min.js")"></script>
    <script src="@Url.Content("~/assets/revolution/js/extensions/revolution.extension.carousel.min.js")"></script>
    <script src="@Url.Content("~/assets/revolution/js/extensions/revolution.extension.kenburn.min.js")"></script>
    <script src="@Url.Content("~/assets/revolution/js/extensions/revolution.extension.layeranimation.min.js")"></script>
    <script src="@Url.Content("~/assets/revolution/js/extensions/revolution.extension.migration.min.js")"></script>
    <script src="@Url.Content("~/assets/revolution/js/extensions/revolution.extension.navigation.min.js")"></script>
    <script src="@Url.Content("~/assets/revolution/js/extensions/revolution.extension.parallax.min.js")"></script>
    <script src="@Url.Content("~/assets/revolution/js/extensions/revolution.extension.slideanims.min.js")"></script>
    <script src="@Url.Content("~/assets/revolution/js/extensions/revolution.extension.video.min.js")"></script>
    <script src="@Url.Content("~/js/custom.js")"></script>
</body>
</html>