DentElora/Controllers/AboutUsController.cs
using DentElora.Data;
using Microsoft.AspNetCore.Mvc;

namespace DentElora.Controllers
{
    public class AboutUsController : Controller
    {
        private readonly DatabaseContext _context;

        public AboutUsController(DatabaseContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var model=_context.AboutUs.FirstOrDefault();
            return View(model);
        }
    }
}

DentElora/Controllers/ContactController.cs
using DentElora.Data;
using Microsoft.AspNetCore.Mvc;

namespace DentElora.Controllers
{
    public class ContactController : Controller
    {
        private readonly DatabaseContext _context;

        public ContactController(DatabaseContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var model = _context.Contacts.FirstOrDefault();
            return View(model);
        }
    }
}

DentElora/Controllers/FaqsController.cs
using DentElora.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace DentElora.Controllers
{
    
    public class FaqsController : Controller
    {
        private readonly DatabaseContext _context;

        public FaqsController(DatabaseContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var model=_context.FAQs.ToList();
            return View(model);
        }
    }
}

DentElora/Controllers/GalleryController.cs
using DentElora.Data;
using Microsoft.AspNetCore.Mvc;

namespace DentElora.Controllers
{
    public class GalleryController : Controller
    {
        private readonly DatabaseContext _context;

        public GalleryController(DatabaseContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var model = _context.Galleries.ToList();
            return View(model);
        }
    }
}

DentElora/Views/Shared/_FooterPartial.cshtml
<!--Start footer area-->
<footer class="footer-area">
    <div class="container">
        <div class="row">
            <!--Start single footer widget-->
            <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
                <div class="single-footer-widget mar-btm">
                    <div class="title">
                        <h3>Hakkımızda</h3>
                        <span class="border"></span>
                    </div>
                    <div class="our-info">
                        <p>How all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound.</p>
                        <ul class="footer-social-links">
                            <li><a href="#"><i class="fa fa-indtagram" aria-hidden="true"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
            <!--End single footer widget-->
            <!--Start single footer widget-->
            <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
                <div class="single-footer-widget mar-lft mar-btm">
                    <div class="title">
                        <h3>Hızlı Linkler</h3>
                        <span class="border"></span>
                    </div>
                    <ul class="quick-links">
                        <li><a asp-controller="Treatments" asp-action="Index">Tedaviler</a></li>
                        <li><a asp-controller="AboutUs" asp-action="Index">Hakkımızda</a></li>
                        <li><a asp-controller="Gallery" asp-action="Index">Galeri</a></li>
                        <li><a asp-controller="Faqs" asp-action="Index">SSS</a></li>
                        <li><a asp-controller="Contact" asp-action="Index">İletişim</a></li>
                    </ul>
                </div>
            </div>
            <!--Start single footer widget-->
            <!--Start single footer widget-->
            <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
                <div class="single-footer-widget martop">
                    <div class="title">
                        <h3>İletişim</h3>
                        <span class="border"></span>
                    </div>
                    <ul class="footer-contact-info">
                        <li>
                            <div class="icon-holder">
                                <span class="flaticon-pin map-marker"></span>
                            </div>
                            <div class="text-holder">
                                <h5>Gümüşpala, 7020. Sk No:15, 35510 Bayraklı/İzmir</h5>
                            </div>
                        </li>
                        <li>
                            <div class="icon-holder">
                                <span class="flaticon-technology-1"></span>
                            </div>
                            <div class="text-holder">
                                <h5>+90 532 532 32 32</h5>
                            </div>
                        </li>
                        <li>
                            <div class="icon-holder">
                                <span class="flaticon-interface"></span>
                            </div>
                            <div class="text-holder">
                                <h5>kolaybahri8910@gmail.com</h5>
                            </div>
                        </li>
                        <li>
                            <div class="icon-holder">
                                <span class="flaticon-clock"></span>
                            </div>
                            <div class="text-holder">
                                <h5>Pzt - Cmt: 10.00 - 18.00</h5>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
            <!--End single footer widget-->
            <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
                <div class="single-footer-widget martop">
                    <div class="title" style="padding-bottom:0px !important">
                        <h3>Sosyal Medya</h3>
                        <span class="border"></span>
                    </div>
                    <div class="top-social-links">
                        <ul style="float:left !important;">
                            <li><a href="#"><i style="font-size:54px !important" class="fa fa-instagram" aria-hidden="true"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>

            <!--Start single footer widget-->
            <div class="col-lg-3 col-md-6 col-sm-6 col-xs-12">
                <div class="single-footer-widget margintop50">
                    <div class="title">
                        <h3>Son İşlemler</h3>
                        <span class="border"></span>
                    </div>
                    
                    <ul class="latest-work-list">
                        <li>
                            <div class="image-holder">
                                <img src="images/footer/latest-work-1.jpg" alt="Awesome Image">
                                <div class="overlay-style-one">
                                    <div class="box">
                                        <div class="content">
                                            <a href="#"><i class="fa fa-link" aria-hidden="true"></i></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="image-holder">
                                <img src="images/footer/latest-work-2.jpg" alt="Awesome Image">
                                <div class="overlay-style-one">
                                    <div class="box">
                                        <div class="content">
                                            <a href="#"><i class="fa fa-link" aria-hidden="true"></i></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="image-holder">
                                <img src="images/footer/latest-work-3.jpg" alt="Awesome Image">
                                <div class="overlay-style-one">
                                    <div class="box">
                                        <div class="content">
                                            <a href="#"><i class="fa fa-link" aria-hidden="true"></i></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="image-holder">
                                <img src="images/footer/latest-work-4.jpg" alt="Awesome Image">
                                <div class="overlay-style-one">
                                    <div class="box">
                                        <div class="content">
                                            <a href="#"><i class="fa fa-link" aria-hidden="true"></i></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="image-holder">
                                <img src="images/footer/latest-work-5.jpg" alt="Awesome Image">
                                <div class="overlay-style-one">
                                    <div class="box">
                                        <div class="content">
                                            <a href="#"><i class="fa fa-link" aria-hidden="true"></i></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                        <li>
                            <div class="image-holder">
                                <img src="images/footer/latest-work-6.jpg" alt="Awesome Image">
                                <div class="overlay-style-one">
                                    <div class="box">
                                        <div class="content">
                                            <a href="#"><i class="fa fa-link" aria-hidden="true"></i></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
            <!--End single footer widget-->

        </div>
    </div>
</footer>
<!--End footer area-->
<!--Start footer bottom area-->
<section class="footer-bottom-area">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="footer-bottom">
                    <div class="copyright-text pull-left">
                        <p>Copyrights © 2025 All Rights Reserved by <a href="#">DentalElora.</a></p>
                    </div>

                </div>
            </div>
        </div>
    </div>
</section>
<!--End footer bottom area-->  

DentElora/Views/Shared/_HeaderPartial.cshtml
<div class="boxed_wrapper">
    <!--Start Preloader -->
    <div class="preloader"></div>
    <!--End Preloader -->
    <!--Start Top bar area -->
    <section class="top-bar-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                   @*  <div class="language-switcher">
                        <div id="polyglotLanguageSwitcher">
                            <form action="#">
                                <select id="polyglot-language-options">
                                    <option id="en" value="en" selected>Türkçe</option>
                                    <option id="fr" value="fr">English</option>
                                    <option id="de" value="de">German</option>
                                    <option id="it" value="it">Italian</option>
                                    <option id="es" value="es">Spanish</option>
                                </select>
                            </form>
                        </div>
                    </div> *@
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                    <div class="logo text-center">
                        <a href="index.html">
                            <img src="/images/resources/dent.png" alt="Awesome Logo">
                        </a>
                    </div>
                </div>
                <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                  @*   <div class="top-social-links">
                        <ul>
                            <li><a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a></li>
                            
                        </ul>
                    </div> *@
                </div>
            </div>
        </div>
    </section>
    <!--End Top bar area -->
    <!--Start mainmenu area-->
    <section class="mainmenu-area stricky">
        <div class="container">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">
                    <div class="left pull-left">
                        <!--Start mainmenu-->
                        <nav class="main-menu">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                            </div>
                            <div class="navbar-collapse collapse clearfix">
                                <ul class="navigation clearfix">
                                    <li class="current"><a asp-controller="Home" asp-action="Index">Anasayfa</a></li>
                                    @await Component.InvokeAsync("Treatment")
                                    <li class="dropdown">
                                        <a asp-controller="AboutUs" asp-action="Index">Hakkımızda</a>
                                       
                                    </li>
                                    <li><a href="/Gallery/Index">Galeri</a></li>
                                    
                                    <li class="dropdown">
                                        <a href="/Faqs/Index">SSS</a>
                                       
                                    </li>
                                    <li><a href="/Contact/Index">İletişim</a></li>
                                </ul>
                            </div>
                        </nav>
                        <!--End mainmenu-->
                        <!--Start outer serach box-->
                        <div class="outer-search-box">
                            <div class="seach-toggle"><i class="fa fa-search"></i></div>
                            <ul class="search-box">
                                <li>
                                    <form method="post" action="index.html">
                                        <div class="form-group">
                                            <input type="search" name="search" placeholder="Arama Yap" required>
                                            <button type="submit"><i class="fa fa-search"></i></button>
                                        </div>
                                    </form>
                                </li>
                            </ul>
                        </div>
                        <!--End outer serach box-->
                    </div>
                    <div class="right pull-right">
                        <div class="icon-box">
                            <span class="flaticon-technology-1"></span>
                        </div>
                        <div class="title-box">
                            <h3>Tel: 0532 532 3232</h3>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--End mainmenu area-->
    <!--Start header area-->
    <header class="mainmenu-bottom-area">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="header-contact-info">
                        <ul>
                            <li>
                                <div class="iocn-holder">
                                    <span class="flaticon-signs"></span>
                                </div>
                                <div class="text-holder">
                                    <h3>Gümüşpala, 7020. Sk No:15, 35510 Bayraklı/İzmir</h3>
                                </div>
                            </li>
                            <li>
                                <div class="iocn-holder">
                                    <span class="flaticon-interface"></span>
                                </div>
                                <div class="text-holder">
                                    <h3>kolaybahri8910@gmail.com</h3>
                                </div>
                            </li>
                            <li>
                                <div class="iocn-holder">
                                    <span class="flaticon-clock"></span>
                                </div>
                                <div class="text-holder">
                                    <h3>Haftalık: 10.00 - 18.00</h3>
                                </div>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!--End header area-->

DentElora/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
   <title>@ViewData["Title"] - DentElora</title>
<meta name="description" content="@ViewData["Description"]" />
<meta name="keywords" content="tedavi, diş tedavisi,implant,dolgu,kanal,diş beyazlatma izmir diş kliniği" />
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/responsive.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css">
   
</head>
<body>
   @*  <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DentElora</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header> *@
    <partial name="_HeaderPartial" />
  
            @RenderBody()
    <!-- _Layout.cshtml dosyanızda body etiketi kapandıktan sonra veya uygun bir yerde ekleyebilirsiniz -->
    <a href="https://wa.me/905320000000?text=Merhaba%2C%20nas%C4%B1l%20yard%C4%B1m%20edebilirim?"
       target="_blank"
       class="whatsapp-float"
       title="WhatsApp ile iletişime geçin">
        <!-- FontAwesome kullanarak ikon eklemek isterseniz: -->
        <i class="bi bi-whatsapp"></i>
        <!-- Veya local bir resim kullanmak için:
        <img src="~/images/whatsapp-icon.png" alt="WhatsApp İkonu" />
        -->
    </a>

    <partial name="_FooterPartial" />
    <!-- main jQuery -->
    <script src="@Url.Content("~/js/jquery.js")"></script>
    <script src="@Url.Content("~/js/wow.min.js")"></script>
    <script src="@Url.Content("~/js/bootstrap.min.js")"></script>
    <script src="@Url.Content("~/js/jquery.bxslider.min.js")"></script>
    <script src="@Url.Content("~/js/jquery.countTo.js")"></script>
    <script src="@Url.Content("~/js/owl.carousel.min.js")"></script>
    <script src="@Url.Content("~/js/validation.js")"></script>
    <script src="@Url.Content("~/js/jquery.mixitup.min.js")"></script>
    <script src="@Url.Content("~/js/jquery.easing.min.js")"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAHzPSV2jshbjI8fqnC_C4L08ffnj5EN3A"></script>
    <script src="@Url.Content("~/js/gmaps.js")"></script>
    <script src="@Url.Content("~/js/map-helper.js")"></script>
    <script src="@Url.Content("~/js/jquery.fitvids.js")"></script>
    <script src="@Url.Content("~/assets/jquery-ui-1.11.4/jquery-ui.js")"></script>
    <script src="@Url.Content("~/assets/language-switcher/jquery.polyglot.language.switcher.js")"></script>
    <script src="@Url.Content("~/js/jquery.fancybox.pack.js")"></script>
    <script src="@Url.Content("~/js/jquery.appear.js")"></script>
    <script src="@Url.Content("~/js/isotope.js")"></script>
    <script src="@Url.Content("~/js/jquery.prettyPhoto.js")"></script>
    <script src="@Url.Content("~/assets/timepicker/timePicker.js")"></script>
    <script src="@Url.Content("~/assets/bootstrap-sl-1.12.1/bootstrap-select.js")"></script>
    <script src="@Url.Content("~/assets/revolution/js/jquery.themepunch.tools.min.js")"></script>
    <script src="@Url.Content("~/assets/revolution/js/jquery.themepunch.revolution.min.js")"></script>
    <script src="@Url.Content("~/assets/revolution/js/extensions/revolution.extension.actions.min.js")"></script>
    <script src="@Url.Content("~/assets/revolution/js/extensions/revolution.extension.carousel.min.js")"></script>
    <script src="@Url.Content("~/assets/revolution/js/extensions/revolution.extension.kenburn.min.js")"></script>
    <script src="@Url.Content("~/assets/revolution/js/extensions/revolution.extension.layeranimation.min.js")"></script>
    <script src="@Url.Content("~/assets/revolution/js/extensions/revolution.extension.migration.min.js")"></script>
    <script src="@Url.Content("~/assets/revolution/js/extensions/revolution.extension.navigation.min.js")"></script>
    <script src="@Url.Content("~/assets/revolution/js/extensions/revolution.extension.parallax.min.js")"></script>
    <script src="@Url.Content("~/assets/revolution/js/extensions/revolution.extension.slideanims.min.js")"></script>
    <script src="@Url.Content("~/assets/revolution/js/extensions/revolution.extension.video.min.js")"></script>
    <script src="@Url.Content("~/js/custom.js")"></script>

</body>
</html>